# Generated by Django 2.2.3 on 2019-07-18 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResizeTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resize_id', models.CharField(blank=True, max_length=255)),
                ('original_img', models.ImageField(upload_to='originals/')),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('resized_img', models.ImageField(blank=True, upload_to='resized/')),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
